"""Readout provenance audit: every collapse-rate number must name its protocol.

Wave v4 produced three independent instances of one failure mode -- a wrong readout
protocol yielding rows that look perfectly valid (argmax on PPO, epsilon=1.0 on the DQN
collapse table, epsilon=1.0 letting central-dqn emit 150 rows at a topology it cannot
run). In all three the numbers were plausible; what was missing was any statement of how
they had been read.

So this is not a one-off check. It scans every report that carries a collapse-rate number
and asserts the file declares its own readout, and it **exits non-zero** when one does
not. From here on, an unlabelled report is a visible failure rather than something
somebody has to remember.

A file is in scope if it contains a collapse-rate table (`seeds collapsed`) or writes a
collapse count in prose ("k dari N seed" / "k of N seeds"). It passes if it carries a
`Readout:` declaration, a VOID/correction banner, a provenance table, or an explicit
in-text protocol name.

Usage:
  python scripts/readout_audit.py
  python scripts/readout_audit.py --out results/READOUT_PROVENANCE.md
"""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SCAN = ["results/**/*.md", "handoff/*.md"]
SKIP_DIRS = {"quarantine_eps1.0"}   # documenting void data is what that directory is for

# A file is in scope if any of these appear.
IN_SCOPE = [
    re.compile(r"seeds collapsed", re.I),
    re.compile(r"\b\d+\s*(?:dari|of)\s*\d+\s*seed", re.I),
    re.compile(r"collapse rate", re.I),
]

# Evidence that the file states how its numbers were read.
DECLARATIONS = {
    # Tolerates blockquote and emphasis around the label ("> **Readout: `greedy`**"), and
    # stops at the closing backtick so the rest of the sentence does not land in the table.
    "readout-line": re.compile(r"^\s*>?\s*[*_]*Readout[*_]*:\s*`([^`]+)`", re.M),
    "void-banner": re.compile(r"VOID FOR THE DQN FAMILY|dikoreksi|corrected", re.I),
    "provenance-table": re.compile(r"Readout provenance", re.I),
    "inline-protocol": re.compile(r"pembacaan primer|primary readout|argmax|epsilon\s*=|ε\s*=", re.I),
}

# Which source directory a report's numbers come from, keyed by filename fragment.
SOURCE = [
    ("STABILITY_v4_dqn_eps005", "results/eval_dqn_eps005", "valid (epsilon=0.05, DQN non-greedy)"),
    ("STABILITY_v4_primary", "results/eval", "valid (primary per family)"),
    ("STABILITY_v4_greedy", "results/eval", "valid (greedy, report-only)"),
    ("STABILITY_v4_stoch", "results/eval", "VOID for DQN (epsilon=1.0)"),
    ("ZEROSHOT_v4_primary", "results/eval_zeroshot_v4", "valid (primary per family)"),
    ("ZEROSHOT_v4_stoch", "results/eval_zeroshot_v4", "VOID for DQN (epsilon=1.0)"),
    ("ZEROSHOT_v4_greedy", "results/eval_zeroshot_v4", "valid (greedy, report-only)"),
    ("ZEROSHOT_v4_knn", "results/eval_zeroshot_v4", "valid (k-NN pilot, post-hoc baseline)"),
    ("STABILITY_local", "results/eval", "superseded (pre-v4 local run)"),
    ("STABILITY.md", "results/eval", "valid (wave v3, reported as pilot per D1)"),
]


def classify(path: Path) -> tuple[str, str]:
    for frag, src, status in SOURCE:
        if frag in path.name:
            return src, status
    return "-", "derived (quotes other reports)"


def declarations_found(text: str) -> list[str]:
    return [name for name, rx in DECLARATIONS.items() if rx.search(text)]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=str, default="results/READOUT_PROVENANCE.md")
    args = p.parse_args()

    rows, unlabelled = [], []
    seen: set[Path] = set()
    for pattern in SCAN:
        for path in sorted(ROOT.glob(pattern)):
            if path in seen or SKIP_DIRS & set(path.parts):
                continue
            seen.add(path)
            text = path.read_text(encoding="utf-8", errors="replace")
            if not any(rx.search(text) for rx in IN_SCOPE):
                continue
            found = declarations_found(text)
            src, status = classify(path)
            m = DECLARATIONS["readout-line"].search(text)
            declared = m.group(1).strip() if m else ("per-row / in-text" if found else "**MISSING**")
            rows.append((path.relative_to(ROOT).as_posix(), declared, src, status))
            if not found:
                unlabelled.append(path.relative_to(ROOT).as_posix())

    lines = [
        "# Readout provenance — every report carrying a collapse-rate number\n",
        "Generated by `scripts/readout_audit.py`. The audit exits non-zero if any report "
        "below carries a collapse number without declaring how it was read, so an "
        "unlabelled report fails visibly instead of quietly.\n",
        "Why this file exists: wave v4 produced three independent cases where a wrong "
        "readout protocol yielded rows that looked valid (`handoff/paper_structure.md` §1). "
        "In none of them were the numbers implausible — what was missing was a statement of "
        "the protocol.\n",
        f"Reports in scope: **{len(rows)}**. Unlabelled: **{len(unlabelled)}**.\n",
        "| report | declared readout | source data | status |",
        "|---|---|---|---|",
    ]
    for rel, declared, src, status in rows:
        lines.append(f"| `{rel}` | {declared} | `{src}` | {status} |")

    lines.append(
        "\n`derived` means the file quotes numbers computed elsewhere rather than reading "
        "eval CSVs itself; it still has to name the protocol it quotes. Files under "
        "`results/quarantine_eps1.0/` are excluded by design.\n")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out}  ({len(rows)} reports in scope, {len(unlabelled)} unlabelled)")
    for rel in unlabelled:
        print(f"  UNLABELLED: {rel}")
    return 1 if unlabelled else 0


if __name__ == "__main__":
    sys.exit(main())
